############################################################
# +------------------------------------------------------+ #
# |                      Messages                        | #
# +------------------------------------------------------+ #
############################################################
Messages:
  non-player-executor: '&cYou can only perform this command as player.'

############################################################
# +------------------------------------------------------+ #
# |                     Autographs                       | #
# +------------------------------------------------------+ #
############################################################
Autographs:
  allow-no-name-autograph: true
  autograph-format:
    - '&7Autograph from &a%player%'